# Generated by Django 5.2.8 on 2025-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collaboration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
